import type { Metadata } from "next";
import { Dosis, Raleway } from "next/font/google";
import "./globals.css";

const geistSans = Dosis({
  variable: "--font-dosis",
  subsets: ["latin"],
  display: "swap",
});

const geistMono = Raleway({
  variable: "--font-raleway",
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
